set_property PACKAGE_PIN W16 [get_ports {in_switch[2]}]
set_property PACKAGE_PIN W17 [get_ports {in_switch[3]}]
set_property PACKAGE_PIN W15 [get_ports {in_switch[4]}]
set_property PACKAGE_PIN V17 [get_ports {in_switch[0]}]
set_property PACKAGE_PIN V16 [get_ports {in_switch[1]}]
set_property PACKAGE_PIN V15 [get_ports {in_switch[5]}]
set_property PACKAGE_PIN L1 [get_ports {out_result[4]}]
set_property PACKAGE_PIN P1 [get_ports {out_result[3]}]
set_property PACKAGE_PIN N3 [get_ports {out_result[2]}]
set_property PACKAGE_PIN P3 [get_ports {out_result[1]}]
set_property PACKAGE_PIN U3 [get_ports {out_result[0]}]
set_property PACKAGE_PIN W19 [get_ports in_boton_1]
set_property PACKAGE_PIN U18 [get_ports in_boton_2]
set_property PACKAGE_PIN T17 [get_ports in_boton_3]

set_property PACKAGE_PIN T18 [get_ports reset]
set_property PACKAGE_PIN W5 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports {in_switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_switch[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_result[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_result[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports in_boton_1]
set_property IOSTANDARD LVCMOS33 [get_ports in_boton_2]
set_property IOSTANDARD LVCMOS33 [get_ports in_boton_3]
set_property IOSTANDARD LVCMOS33 [get_ports reset]


set_property IOSTANDARD LVCMOS33 [get_ports in_boton_4]
set_property PACKAGE_PIN U17 [get_ports in_boton_4]
